# Generated by Django 5.0.8 on 2024-08-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0003_alter_schedules_end_hour_alter_schedules_start_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaccess',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='weekly_day',
            field=models.CharField(max_length=100),
        ),
    ]
