# Generated by Django 5.0.8 on 2024-08-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigate', '0004_alter_logaccess_date_alter_schedules_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=14)),
                ('weekly_day', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('start_hour', models.CharField(max_length=100)),
                ('end_hour', models.CharField(max_length=100)),
                ('modality', models.CharField(max_length=100)),
            ],
        ),
    ]
